Repository woowacourse-teams/2023-map-befine, pull requests merged in 2023-08, with the labels that each got.

#118 [BE] Truncate 를 위한 DatabaseCleanup 구현
  backend/src/test/java/com/mapbefine/mapbefine/DatabaseCleanup.java
  backend/src/test/java/com/mapbefine/mapbefine/integration/IntegrationTest.java
Labels: BE, 우선순위 : 중, refactor

#144 [FE]Refactor/#143 토픽 같이보기 기능 추가된 명세에 맞게 수정 및 context 코드 변경
  frontend/src/App.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/context/MarkerContext.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/store/TagId.tsx
  frontend/src/store/TopicsId.tsx
Labels: FE, refactor

#146 [FE] 프론트 CI/CD workflows 수정
  .github/workflows/fe-merge-dev.yml
  .github/workflows/fe-merge-prod.yml
Labels: FE, Infra, 우선순위 : 중

#148 [FE]Refactor/#147 토픽 카드 이미지 적용 및 blur처리
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/common/Box/index.ts
Labels: FE, refactor

#149 [FE] CI/CD workflows 코드 재수정
  .github/workflows/fe-merge-dev.yml
  .github/workflows/fe-merge-prod.yml
Labels: FE, Infra, 우선순위 : 중, refactor

#154 [FE]Refactor/#147 토픽 카드 이미지 적용 및 blur처리
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/common/Box/index.ts
Labels: FE, refactor

#159 [FE]Refactor/#147 토픽 카드 이미지 적용 및 blur처리
  frontend/package.json
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/common/Box/index.ts
Labels: FE, refactor

#160 [FE] CI/CD workflows 코드 수정
  .github/workflows/fe-merge-dev.yml
  .github/workflows/fe-merge-prod.yml
Labels: FE, Infra, refactor

#163 [FE]Refactor/#147 토픽 카드 이미지 적용 및 blur처리
  frontend/package.json
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/common/Box/index.ts
Labels: FE, refactor

#166 [FE]Refactor/#147 토픽 카드 이미지 적용 및 blur처리
  frontend/package.json
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/common/Box/index.ts
Labels: FE, refactor

#171 [BE] CORS 허용 Origin에 개발서버, 운영서버 도메인 추가
  backend/src/main/java/com/mapbefine/mapbefine/config/WebMvcConfig.java
Labels: bug, BE

#174 [BE] CORS 허용 여러 Origin 모두 설정하도록 수정
  backend/src/main/java/com/mapbefine/mapbefine/config/WebMvcConfig.java
Labels: bug, BE

#179 [FE] Refactor/#168 전반적인 레이아웃 및 UI 오류 수정
  frontend/src/components/Layout/index.tsx
  frontend/src/components/Map.tsx
  frontend/src/components/MergeOrSeeTogether/index.tsx
  frontend/src/components/PinPreview/index.stories.ts
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.stories.ts
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/components/common/Box/index.stories.ts
  frontend/src/components/common/Box/index.ts
  frontend/src/components/common/Button/index.stories.ts
  frontend/src/components/common/Flex/index.ts
  frontend/src/components/common/Input/index.stories.ts
  frontend/src/components/common/Text/index.stories.ts
  frontend/src/components/common/Textarea/index.stories.ts
  frontend/src/hooks/useGeolocation.ts
  frontend/src/mocks/db/tempPins.js
  frontend/src/pages/Home.stories.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.stories.ts
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/store/TagId.tsx
  frontend/src/themes/color.ts
  frontend/src/themes/fontSize.ts
  frontend/src/themes/fontWeight.ts
  frontend/src/themes/index.ts
  frontend/src/themes/radius.ts
  frontend/src/themes/spacing.ts
  frontend/src/types/index.d.ts
  frontend/src/utils/getApi.ts
  frontend/src/utils/postApi.ts
  frontend/src/utils/putApi.ts
Labels: FE, refactor

#178 [FE]Refactor/#169 불필요한 코드, 컨텍스트 제거
  frontend/src/App.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/store/TagId.tsx
Labels: FE, refactor

#181 [FE]Fix/#167 전반적인 지도 오류 수정 및 개선
  frontend/package-lock.json
  frontend/public/mockServiceWorker.js
  frontend/src/components/Map.tsx
  frontend/src/context/MarkerContext.tsx
  frontend/src/pages/SelectedTopic.tsx
Labels: bug, FE

#183 [FE]Refactor/#145 UI 조정 및 머지 후 자잘한 오류 수정
  frontend/src/components/MergeOrSeeTogether/index.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/Tag/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/components/common/Box/index.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/pages/UpdatedPinDetail.tsx
Labels: FE, 우선순위 : 상, refactor

#188 [FE]Feature/#184 웹 접근성 대상 선정 및 개선
  frontend/src/components/Layout/Logo.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/components/MergeOrSeeTogether/index.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
Labels: FE, feat

#192 [FE]Fix#191 같이보기 상태에서 핀 추가시 발생하는 오류 수정
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/SelectedTopic.tsx
Labels: bug, FE, 우선순위 : 상

#193 [FE]FIX/#191 같이 보기에서 핀 클릭 시 같이 보기가 풀리는 오류 수정
  frontend/src/components/PinPreview/index.tsx
  frontend/src/pages/SelectedTopic.tsx
Labels: bug, FE, 우선순위 : 상

#197 [FE]Refactor/#196 줌 레벨 제한
  frontend/src/components/Layout/index.tsx
  frontend/src/hooks/useAnimateClickedPin.ts
Labels: FE, refactor

#199 [FE]Feature/#184 웹 접근성 개선
  frontend/src/components/Layout/Logo.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/pages/Home.tsx
Labels: FE, feat

#206 [FE]Feature/#205 Toast 컴포넌트 구현 및 기존 alert 대체
  frontend/src/components/Layout/index.tsx
  frontend/src/components/Toast/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/components/common/Text/index.ts
  frontend/src/constants/index.ts
  frontend/src/context/ToastContext.tsx
  frontend/src/hooks/useToast.ts
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/types/Toast.ts
Labels: FE, 우선순위 : 중, feat

#208 [FE]Refactor/#207 전반적인 코드 리팩토링 및 추상화
  frontend/src/GlobalStyle.ts
  frontend/src/apis/getApi.ts
  frontend/src/apis/postApi.ts
  frontend/src/apis/putApi.ts
  frontend/src/components/Layout/index.tsx
  frontend/src/components/Map/index.tsx
  frontend/src/components/Tag/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/common/Box/index.ts
  frontend/src/components/common/Button/index.ts
  frontend/src/components/common/Flex/index.ts
  frontend/src/components/common/Image/index.ts
  frontend/src/components/common/Input/index.ts
  frontend/src/components/common/Space/index.ts
  frontend/src/components/common/Text/index.ts
  frontend/src/components/common/Textarea/index.ts
  frontend/src/constants/pinImage.ts
  frontend/src/context/MarkerContext.tsx
  frontend/src/lib/getAddressFromServer.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/pages/UpdatedPinDetail.tsx
  frontend/src/utils/getAddress.ts
  frontend/src/utils/getApi.ts
Labels: FE, 우선순위 : 하, refactor

#242 [FE]Refactor/#231,#228,#217 전반적인 지도 UI 문제 해결
  frontend/public/index.html
  frontend/src/components/Layout/index.tsx
  frontend/src/context/MarkerContext.tsx
  frontend/src/hooks/useAnimateClickedPin.ts
  frontend/src/hooks/useClickedCoordinate.ts
  frontend/src/hooks/useFocusToMarkers.ts
  frontend/src/types/index.d.ts
Labels: bug, FE

#244 [FE] Refactor/#241 PinDetail 페이지 UI 및 관련 로직 수정, 공용 모달 구현
  frontend/src/assets/plus.svg
  frontend/src/assets/share.svg
  frontend/src/context/ModalContext.tsx
  frontend/src/index.tsx
  frontend/src/pages/PinDetail.tsx
Labels: FE, refactor

#246 [FE] Refactor/#245 하단 바 및 선택된 토픽 UI 수정
  frontend/src/GlobalStyle.ts
  frontend/src/assets/All.svg
  frontend/src/assets/Back.svg
  frontend/src/assets/Favorite.svg
  frontend/src/assets/Home.svg
  frontend/src/assets/Keep.svg
  frontend/src/assets/Share2.svg
  frontend/src/assets/Star.svg
  frontend/src/assets/Star2.svg
  frontend/src/assets/addButton.svg
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/pages/Home.tsx
Labels: FE, refactor

#243 [FE]Feature/#236 홈 UI 재배치 및 같이보기 페이지 구현
  frontend/src/components/Layout/index.tsx
  frontend/src/components/Map/index.tsx
  frontend/src/components/SeeAllCardList/index.tsx
  frontend/src/components/SeeTogetherButton/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicCardList/index.tsx
  frontend/src/components/TopicListContainer/index.tsx
  frontend/src/context/LayoutWidthContext.tsx
  frontend/src/context/SeeTogetherContext.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/RootPage.tsx
  frontend/src/pages/SeeAllTopics.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/router.tsx
Labels: FE, 우선순위 : 상, feat

#247 [FE] 머지 과정에서 누락된 import 추가
  frontend/src/components/Layout/index.tsx
Labels: bug, FE

#237 [BE] Member 관련 기능 개발
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/main/java/com/mapbefine/mapbefine/auth/application/AuthService.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/domain/AuthMember.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberTopicPermission.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberTopicPermissionRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/Role.java
  backend/src/main/java/com/mapbefine/mapbefine/member/dto/request/MemberCreateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/member/dto/request/MemberTopicPermissionCreateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/member/dto/response/MemberDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/member/dto/response/MemberResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/member/dto/response/MemberTopicPermissionDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/member/dto/response/MemberTopicPermissionResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinInfo.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicInfo.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
  backend/src/test/java/com/mapbefine/mapbefine/common/RestDocsIntegration.java
  backend/src/test/java/com/mapbefine/mapbefine/location/application/LocationQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/domain/LocationRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/domain/LocationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/presentation/LocationControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/MemberFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberDetailResponseTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberInfoTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberResponseTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberTopicPermissionTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/PinFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/PinIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinImageTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicInfoTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Labels: BE, 우선순위 : 중, feat, refactor

#249 [FE]Refactor/#248 지도 버전 변경 반영
  frontend/src/context/MarkerContext.tsx
  frontend/src/hooks/useMapClick.ts
  frontend/src/pages/NewPin.tsx
Labels: FE, refactor

#238 [BE] Topic 패키지 관련 코드 리팩토링
  backend/src/main/java/com/mapbefine/mapbefine/common/entity/Image.java
  backend/src/main/java/com/mapbefine/mapbefine/location/domain/Address.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinImage.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicInfo.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicStatus.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/dto/request/TopicUpdateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
  backend/src/test/java/com/mapbefine/mapbefine/common/entity/ImageTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/LocationIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/domain/LocationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/MemberFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/PinIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicInfoTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicStatusTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Labels: BE, 우선순위 : 중, refactor

#202 [FE]Feature/#201 프론트 테스트 자동화
  .github/workflows/fe-pull-request.yml
Labels: Infra

#256 [FE] Feature/#204 입력 폼 유효성 검사
  frontend/package.json
  frontend/src/components/InputContainer/index.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/common/Input/index.ts
  frontend/src/components/common/Textarea/index.ts
  frontend/src/hooks/useFormValues.ts
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/pages/UpdatedPinDetail.tsx
  frontend/src/types/FormValues.ts
  frontend/src/validations/index.ts
Labels: FE, 우선순위 : 상, feat

#268 [FE] feature/#266 이미지, 툴팁 공통 컴포넌트 구현
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/common/ShapeImage/index.tsx
  frontend/src/components/common/Tooltip/index.tsx
Labels: FE, feat

#273 [BE] env/#272 CI/CD 테스트를 위한 환경변수 설정 추가
  .github/workflows/be-merge-dev.yml
  .github/workflows/be-merge-prod.yml
  .github/workflows/be-pull-request.yml
Labels: BE, env

#278 [FE] feature/#267 Suspense, ErrorBoundary, ErrorHandling 작업 구현
  frontend/src/apis/getMapApi.ts
  frontend/src/assets/LoginErrorIcon.svg
  frontend/src/assets/NotFoundIcon.svg
  frontend/src/components/ErrorBoundary/ApiErrorBoundary.tsx
  frontend/src/components/ErrorBoundary/index.tsx
  frontend/src/components/Loader/index.tsx
  frontend/src/components/NotFound/LoginError.tsx
  frontend/src/components/NotFound/index.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/PinsOfTopic/PinsOfTopicSkeleton.tsx
  frontend/src/components/PinsOfTopic/index.tsx
  frontend/src/components/SeeAllCardList/SeeAllCardListSkeleton.tsx
  frontend/src/components/TopicCardList/TopicCardListSeleton.tsx
  frontend/src/components/TopicListContainer/index.tsx
  frontend/src/components/common/PinSkeleton/index.tsx
  frontend/src/components/common/TopicSkeleton/index.tsx
  frontend/src/hooks/useMapClick.ts
  frontend/src/lib/getAddressFromServer.ts
  frontend/src/pages/SeeAllTopics.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/router.tsx
  frontend/tsconfig.json
Labels: FE, feat

#281 [FE] feature/#259 로그인 버튼 구현 (관련 리다이렉트 설정), 토큰 관련 작업
  frontend/src/apis/getApi.ts
  frontend/src/assets/My.svg
  frontend/src/components/Layout/AuthLayout.tsx
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/pages/AskLoginPage.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/KaKaoRedirectPage.tsx
  frontend/src/pages/MoaBogi.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/Zzlegyeo.tsx
  frontend/src/router.tsx
  frontend/src/types/Login.ts
Labels: FE, feat

#277 [BE] feature/#255 소셜로그인 구현
  backend/build.gradle
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/docs/asciidoc/oauth.adoc
  backend/src/docs/asciidoc/pin.adoc
  backend/src/docs/asciidoc/topic.adoc
  backend/src/main/java/com/mapbefine/mapbefine/MapbefineApplication.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/application/AuthService.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/dto/AuthInfo.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/BasicAuthorizationExtractor.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/BearerAuthorizationExtractor.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java
  backend/src/main/java/com/mapbefine/mapbefine/common/config/HttpInterfaceConfig.java
  backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java
  backend/src/main/java/com/mapbefine/mapbefine/common/converter/OauthServerTypeConverter.java
  backend/src/main/java/com/mapbefine/mapbefine/common/interceptor/AuthInterceptor.java
  backend/src/main/java/com/mapbefine/mapbefine/common/resolver/AuthArgumentResolver.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/OauthId.java
  backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/application/OauthService.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/AuthCodeRequestUrlProvider.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/AuthCodeRequestUrlProviderComposite.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/OauthMember.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/OauthMemberClient.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/OauthMemberClientComposite.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/OauthServerType.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/kakao/KakaoApiClient.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/kakao/KakaoAuthCodeRequestUrlProvider.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/kakao/KakaoMemberClient.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/kakao/KakaoOauthProperties.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/kakao/dto/KakaoMemberResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/kakao/dto/KakaoToken.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/dto/LoginInfoResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/presentation/OauthController.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/mapbefine/mapbefine/common/IntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/RestDocsIntegration.java
  backend/src/test/java/com/mapbefine/mapbefine/common/TestAuthHeaderProvider.java
  backend/src/test/java/com/mapbefine/mapbefine/common/annotation/ServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/config/MockBeansConfig.java
  backend/src/test/java/com/mapbefine/mapbefine/location/LocationFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/location/application/LocationQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/domain/LocationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/MemberFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/oauth/application/OauthServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/oauth/presentation/OauthControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/PinIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
  backend/src/test/resources/application.yml
Labels: BE, 우선순위 : 중, feat, test

#280 [BE] refactor/#279 permission 패키지 분리
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/docs/asciidoc/permission.adoc
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberTopicPermissionRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/member/dto/request/MemberTopicPermissionCreateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/member/dto/response/MemberTopicPermissionDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/member/dto/response/MemberTopicPermissionResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/presentation/OauthController.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/domain/Permission.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/domain/PermissionRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/dto/request/PermissionRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/dto/response/PermissionDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/dto/response/PermissionResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/presentation/PermissionController.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/PermissionType.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicStatus.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/dto/request/TopicCreateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/dto/request/TopicMergeRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/dto/request/TopicUpdateRequest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/PermissionIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/application/PermissionCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/application/PermissionQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/domain/PermissionTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/presentation/PermissionControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/PermissionTypeTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicStatusTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Labels: BE, 우선순위 : 중, refactor

#284 [FE] fix/#283 소셜 로그인 url 변경
  frontend/src/pages/AskLoginPage.tsx
  frontend/src/pages/KaKaoRedirectPage.tsx
Labels: FE, env

#286 hotfix: https로 수정
  frontend/src/pages/AskLoginPage.tsx
  frontend/src/pages/KaKaoRedirectPage.tsx
  frontend/src/pages/My.tsx
  frontend/src/router.tsx
Labels: bug, FE

#289 hotfix: function-async
  frontend/src/pages/KaKaoRedirectPage.tsx
Labels: bug, FE

#275 [BE] feature/#264 토픽에 대한 즐겨찾기 API
  backend/src/docs/asciidoc/bookmark.adoc
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/member.adoc
  backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/Bookmark.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
  backend/src/main/java/com/mapbefine/mapbefine/location/application/LocationQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicWithBookmarkStatus.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/TopicResponse.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/application/BookmarkQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/IntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/config/MockBeansConfig.java
  backend/src/test/java/com/mapbefine/mapbefine/location/application/LocationQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/presentation/LocationControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/PermissionIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/application/PermissionCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/PinIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Labels: BE, 우선순위 : 중, feat

#292 hotfix: url에 api 추가
  frontend/src/pages/KaKaoRedirectPage.tsx
Labels: FE

#299 [BE] refactor 인증 인가 관련 수정
  backend/src/docs/asciidoc/bookmark.adoc
  backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/BearerAuthorizationExtractor.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/mapbefine/mapbefine/common/TestAuthHeaderProvider.java
  backend/src/test/java/com/mapbefine/mapbefine/location/presentation/LocationControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/oauth/presentation/OauthControllerTest.java
Labels: BE, refactor

#303 [FE] feature/#282 내 정보 관련 컴포넌트 구현 및 getApi 타입 지정
  frontend/src/assets/InfoDefalutImg.svg
  frontend/src/assets/ModifyMyInfoIcon.svg
  frontend/src/components/MyInfo/UpdateMyInfo.tsx
  frontend/src/components/MyInfo/index.tsx
  frontend/src/components/SeeAllCardList/index.tsx
  frontend/src/components/TopicCardList/index.tsx
  frontend/src/hooks/useFormValues.ts
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/types/MyInfo.ts
  frontend/src/types/Pin.ts
Labels: FE, feat

#312 [BE] hotfix/#311 일부 API 명세 변경, 개발서버 구성환경 수정, 인가 관련 예외 처리
  backend/src/docs/asciidoc/member.adoc
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
  backend/src/main/java/com/mapbefine/mapbefine/common/interceptor/AuthInterceptor.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/dto/request/PermissionRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/presentation/PermissionController.java
  backend/src/main/resources/application-dev.yml
  backend/src/test/java/com/mapbefine/mapbefine/atlas/presentation/AtlasControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/BookmarkIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/TestAuthHeaderProvider.java
  backend/src/test/java/com/mapbefine/mapbefine/location/presentation/LocationControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/PermissionIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/application/PermissionCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/presentation/PermissionControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Labels: BE, 우선순위 : 상, refactor

#270 [BE] feature/#253 특정 핀에 대해 내 지도에 저장하기 API
  backend/src/docs/asciidoc/topic.adoc
  backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/BearerAuthorizationExtractor.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
  backend/src/test/java/com/mapbefine/mapbefine/atlas/application/AtlasQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/atlas/presentation/AtlasControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/TestAuthHeaderProvider.java
  backend/src/test/java/com/mapbefine/mapbefine/location/application/LocationQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/presentation/LocationControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/presentation/PermissionControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Labels: BE, 우선순위 : 중, feat, test

#306 [BE] feature/#298 인기 (급상승) 토픽 조회 API
  backend/src/docs/asciidoc/topic.adoc
  backend/src/main/java/com/mapbefine/mapbefine/atlas/presentation/AtlasController.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkController.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
  backend/src/test/java/com/mapbefine/mapbefine/atlas/AtlasIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/atlas/presentation/AtlasControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/presentation/LocationControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/MemberIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/PermissionIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/PinIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Labels: BE, 우선순위 : 중, feat

#308 [FE] feature/#300 즐겨찾기 페이지 구현
  frontend/src/components/BookmarksContainer/BookmarksList/index.tsx
  frontend/src/components/BookmarksContainer/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/pages/Bookmark.tsx
  frontend/src/router.tsx
  frontend/src/types/Bookmarks.ts
Labels: FE, 우선순위 : 상, feat

#309 [FE] feature/#301 내 정보 페이지 구현
  frontend/src/assets/InfoDefalutImg.svg
  frontend/src/components/Layout/index.tsx
  frontend/src/components/MyInfo/index.tsx
  frontend/src/components/MyInfoContainer/MyInfoList/index.tsx
  frontend/src/components/MyInfoContainer/index.tsx
  frontend/src/components/NotFound/LoginError.tsx
  frontend/src/components/PinCard/index.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/router.tsx
  frontend/src/types/MyInfo.ts
Labels: FE, 우선순위 : 상, feat

#307 [FE] Feature/#304 모아보기 구현
  frontend/src/apis/deleteApi.ts
  frontend/src/apis/postApi.ts
  frontend/src/assets/favoriteBtn_notFilled.svg
  frontend/src/assets/seeTogetherBtn_notFilled.svg
  frontend/src/assets/topicInfo_favoriteBtn_fiiled.svg
  frontend/src/assets/topicInfo_favoriteBtn_notFilled.svg
  frontend/src/assets/topicInfo_seeTogetherBtn_filled.svg
  frontend/src/assets/topicInfo_seeTogetherBtn_notFilled.svg
  frontend/src/components/AddSeeTogether/index.tsx
  frontend/src/components/Layout/AuthLayout.tsx
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/PinsOfTopic/index.tsx
  frontend/src/components/PullPin/index.tsx
  frontend/src/components/SeeAllCardList/index.tsx
  frontend/src/components/SeeTogetherCounter/index.tsx
  frontend/src/components/Toast/index.tsx
  frontend/src/components/TopicCard/TopicCard.stories.ts
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicCardList/index.tsx
  frontend/src/components/TopicInfo/index.stories.ts
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/context/SeeTogetherContext.tsx
  frontend/src/context/TagContext.tsx
  frontend/src/pages/ErrorPage.tsx
  frontend/src/pages/MoaBogi.tsx
  frontend/src/pages/My.tsx
  frontend/src/pages/SeeAllPopularTopics.tsx
  frontend/src/pages/SeeTogetherTopics.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/pages/Zzlegyeo.tsx
  frontend/src/router.tsx
  frontend/src/types/Pin.ts
  frontend/src/types/Tag.ts
  frontend/src/types/Topic.ts
Labels: FE, 우선순위 : 상, feat

#318 [FE] Feature/#317 권한 관련 기능 구현
  frontend/src/apis/getApi.ts
  frontend/src/apis/postApi.ts
  frontend/src/components/AddFavorite/index.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/components/TopicCardList/index.tsx
  frontend/src/components/common/CheckBox/index.tsx
  frontend/src/context/MarkerContext.tsx
  frontend/src/hooks/useUpdateCoordinates.ts
  frontend/src/index.tsx
  frontend/src/pages/KaKaoRedirectPage.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/pages/UpdatedPinDetail.tsx
  frontend/src/router.tsx
Labels: FE, feat

#320 [FE] fix: 버그 일괄 수정
  frontend/src/components/Layout/index.tsx
  frontend/src/components/MyInfoContainer/MyInfoList/index.tsx
  frontend/src/pages/Profile.tsx
Labels: bug, FE

#332 [FE] feature/#331 권한있는 토픽 접근 가능 기능 구현
  frontend/src/apis/postApi.ts
  frontend/src/components/Layout/index.tsx
  frontend/src/components/ModalMyTopicList/addToMyTopicList.tsx
  frontend/src/components/ModalMyTopicList/index.tsx
  frontend/src/components/ModalTopicCard/index.tsx
  frontend/src/hooks/useUpdateCoordinates.ts
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
Labels: FE, feat

#327 [FE] feature/#325 웹 접근성 적용
  frontend/src/components/Layout/Logo.tsx
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Map/index.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/components/Toast/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/components/TopicListContainer/index.tsx
  frontend/src/components/common/CheckBox/index.tsx
  frontend/src/hooks/useKeyDown.ts
  frontend/src/pages/NewTopic.tsx
Labels: FE, 우선순위 : 상, feat

#333 [FE] Refactor/#324
  frontend/public/index.html
  frontend/src/apis/getApi.ts
  frontend/src/apis/postApi.ts
  frontend/src/apis/putApi.ts
  frontend/src/assets/topicInfo_favoriteBtn_filled.svg
  frontend/src/components/AddFavorite/index.tsx
  frontend/src/components/BookmarksContainer/BookmarksList/index.tsx
  frontend/src/components/BookmarksContainer/index.tsx
  frontend/src/components/BookmarksList/index.tsx
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/ModalMyTopicList/index.tsx
  frontend/src/components/ModalTopicCard/index.tsx
  frontend/src/components/MyInfo/index.tsx
  frontend/src/components/MyInfoContainer/index.tsx
  frontend/src/components/PinPreviewSkeleton/index.tsx
  frontend/src/components/PinsOfTopic/PinsOfTopicSkeleton.tsx
  frontend/src/components/PinsOfTopic/index.tsx
  frontend/src/components/SeeAllCardList/SeeAllCardListSkeleton.tsx
  frontend/src/components/SeeAllCardList/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicCardList/TopicCardListSeleton.tsx
  frontend/src/components/TopicCardList/TopicCardListSkeleton.tsx
  frontend/src/components/TopicCardList/index.tsx
  frontend/src/components/TopicCardSkeleton/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/components/TopicInfoSkeleton/index.tsx
  frontend/src/components/TopicListContainer/index.tsx
  frontend/src/constants/pinImage.ts
  frontend/src/context/MarkerContext.tsx
  frontend/src/pages/Bookmark.tsx
  frontend/src/pages/Favorite.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SeeAllLatestTopics.tsx
  frontend/src/pages/SeeAllNearTopics.tsx
  frontend/src/pages/SeeAllPopularTopics.tsx
  frontend/src/pages/SeeTogetherTopics.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/utils/getCurrentLocation.ts
Labels: FE, 우선순위 : 상, refactor

#334 [BE] feature/#330 로깅 적용
  backend/.gitignore
  backend/src/main/java/com/mapbefine/mapbefine/common/GlobalExceptionHandler.java
  backend/src/main/java/com/mapbefine/mapbefine/common/config/TimeZoneConfig.java
  backend/src/main/java/com/mapbefine/mapbefine/common/entity/Image.java
  backend/src/main/java/com/mapbefine/mapbefine/common/interceptor/AuthInterceptor.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
  backend/src/test/java/com/mapbefine/mapbefine/common/entity/ImageTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/logback-test.xml
Labels: BE, feat

#337 [BE] hotfix/log 로그인 버그로 인한 인터셉터 수정 및 로그백 일부 수정
  backend/src/main/java/com/mapbefine/mapbefine/common/interceptor/AuthInterceptor.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/logback-spring.xml
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
Labels: bug, BE, 우선순위 : 상

#339 [FE] Fix/all
  frontend/src/components/AddSeeTogether/index.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/components/ModalMyTopicList/addToMyTopicList.tsx
  frontend/src/components/ModalMyTopicList/index.tsx
  frontend/src/components/ModalTopicCard/index.tsx
  frontend/src/components/PinsOfTopic/index.tsx
  frontend/src/components/PullPin/index.tsx
  frontend/src/components/SeeTogetherCounter/index.tsx
  frontend/src/constants/index.ts
  frontend/src/context/SeeTogetherContext.tsx
  frontend/src/index.tsx
  frontend/src/pages/Bookmark.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/KaKaoRedirectPage.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/SeeTogetherTopics.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/router.tsx
  frontend/src/types/Topic.ts
Labels: bug, FE, 우선순위 : 상, feat

#340 [FE] Fix/all
  frontend/package.json
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/PinDetail.tsx
Labels: bug, FE, 우선순위 : 상, refactor

#341 [BE] hotfix/guest 게스트 조회시 발생하던 버그 해결
  backend/src/main/java/com/mapbefine/mapbefine/location/application/LocationQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/location/presentation/LocationController.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
Labels: bug, BE, 우선순위 : 상

#344 [FE] Fix/chore-things
  frontend/src/apis/putApi.ts
  frontend/src/components/AddFavorite/index.tsx
  frontend/src/components/AddSeeTogether/index.tsx
  frontend/src/pages/Bookmark.tsx
  frontend/src/pages/KaKaoRedirectPage.tsx
  frontend/src/pages/SeeTogetherTopics.tsx
  frontend/src/pages/UpdatedPinDetail.tsx
Labels: FE, 우선순위 : 상, refactor

#345 [FE] fix: 로그인 후 새로고침 로직 수정
  frontend/src/pages/KaKaoRedirectPage.tsx
Labels: bug, FE

#342 [BE] feature/nickname 랜덤 닉네임에 고정 문자열 대신 카카오 닉네임 사용
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/OauthMember.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/kakao/dto/KakaoMemberResponse.java
  backend/src/test/java/com/mapbefine/mapbefine/oauth/application/OauthServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/oauth/domain/OauthMemberTest.java
Labels: BE, feat

#343 [BE] refactor/#388 ErrorCode 내 Info 추가
  backend/src/main/java/com/mapbefine/mapbefine/atlas/exception/AtlasErrorCode.java
  backend/src/main/java/com/mapbefine/mapbefine/atlas/exception/AtlasException.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/exception/BookmarkException.java
  backend/src/main/java/com/mapbefine/mapbefine/common/GlobalExceptionHandler.java
  backend/src/main/java/com/mapbefine/mapbefine/common/exception/BadRequestException.java
  backend/src/main/java/com/mapbefine/mapbefine/common/exception/ConflictException.java
  backend/src/main/java/com/mapbefine/mapbefine/common/exception/ErrorCode.java
  backend/src/main/java/com/mapbefine/mapbefine/common/exception/ForbiddenException.java
  backend/src/main/java/com/mapbefine/mapbefine/common/exception/GlobalException.java
  backend/src/main/java/com/mapbefine/mapbefine/common/exception/NotFoundException.java
  backend/src/main/java/com/mapbefine/mapbefine/common/exception/UnauthorizedException.java
  backend/src/main/java/com/mapbefine/mapbefine/common/exception/dto/ErrorResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/location/exception/LocationException.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/exception/MemberException.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/AuthCodeRequestUrlProviderComposite.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/domain/OauthMemberClientComposite.java
  backend/src/main/java/com/mapbefine/mapbefine/oauth/exception/OathException.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/exception/PermissionException.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/exception/PinException.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/exception/TopicException.java
Labels: BE, 우선순위 : 중, refactor

#328 [FE] feature/#326 cypress 설정 및 적용
  frontend/cypress.config.ts
  frontend/cypress/e2e/mapbefine.cy.ts
  frontend/cypress/fixtures/example.json
  frontend/cypress/support/commands.ts
  frontend/cypress/support/e2e.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/tsconfig.json
Labels: FE, 우선순위 : 상, feat

#347 [FE] refactor: 에러 토스트 메시지 변경 및 스크롤 에러 수정
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/MyInfoContainer/MyInfoList/index.tsx
  frontend/src/pages/LoginError.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
Labels: FE, 우선순위 : 상, refactor

#348 [FE] refactor: 에러 메시지 및 에러 해결
  frontend/src/components/ModalMyTopicList/addToMyTopicList.tsx
  frontend/src/components/ModalMyTopicList/index.tsx
  frontend/src/components/ModalTopicCard/index.tsx
  frontend/src/pages/NewTopic.tsx
Labels: bug, FE, 우선순위 : 상

#350 [FE] cypress test 추가 및 자동 배포 적용
  .github/workflows/fe-pull-request.yml
  frontend/cypress/e2e/mapbefine.cy.ts
Labels: FE, 우선순위 : 상, test

#351 [FE] test: cypress 자동 배포 설정
  .github/workflows/fe-pull-request.yml
Labels: FE, 우선순위 : 상, test

#352 [FE] test: cypress 테스트 자동화
  .github/workflows/fe-pull-request.yml
Labels: FE, test

#354 hotfix: 서버 요청 도메인 분리
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/deleteApi.ts
  frontend/src/apis/getApi.ts
  frontend/src/apis/postApi.ts
  frontend/src/apis/putApi.ts
  frontend/webpack.common.js
Labels: FE, 우선순위 : 상

#357 [FE] test: 사이프레스 자동화
  .github/workflows/fe-pull-request.yml
Labels: FE, test

#356 hotfix: api 분리
  .github/workflows/fe-merge-dev.yml
  .github/workflows/fe-merge-prod.yml
  frontend/.gitignore
  frontend/package-lock.json
  frontend/package.json
  frontend/src/apis/getApi.ts
  frontend/src/apis/postApi.ts
  frontend/src/apis/putApi.ts
  frontend/webpack.common.js
Labels: FE, env

#358 [FE] Hotfix:api response 변경
  .github/workflows/fe-merge-dev.yml
  .github/workflows/fe-merge-prod.yml
  frontend/src/pages/KaKaoRedirectPage.tsx
Labels: FE, env

#364 [FE] Chore/#363 main hotfixes 커밋 반영
  .github/workflows/fe-pull-request.yml
  frontend/cypress/e2e/mapbefine.cy.ts
Labels: FE, refactor
