Repository woowacourse-teams/2023-map-befine, pull requests merged in 2023-10, with the labels that each got.

#539 [BE] Hotfix/#537,#538 회원 정보 관련 이슈 해결
  backend/src/main/java/com/mapbefine/mapbefine/auth/domain/AuthMember.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/domain/member/Admin.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/domain/member/Guest.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/domain/member/User.java
  backend/src/main/java/com/mapbefine/mapbefine/common/interceptor/AuthInterceptor.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/dto/response/MemberResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/member/exception/MemberErrorCode.java
  backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
  backend/src/main/resources/data-default.sql
  backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/domain/MemberResponseTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/presentation/PermissionControllerTest.java
Labels: bug, BE, 우선순위 : 상

#542 [FE] Refactor/#541 비로그인 시 pin image button 숨기기
  frontend/src/pages/PinDetail.tsx
Labels: FE, 우선순위 : 상, refactor

#555 [FE] Feat/#554 search 지도 검색 기능 구현
  frontend/src/assets/search.svg
  frontend/src/components/SearchBar/SearchBar.tsx
  frontend/src/hooks/useNavigator.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/Search.tsx
  frontend/src/router.tsx
Labels: FE, 우선순위 : 상, feat

#516 [FE] refactor/#450 모아보기 기능 비회원도 가능하도록 수정
  frontend/src/components/AddSeeTogether/index.tsx
  frontend/src/components/SeeTogetherCounter/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/context/SeeTogetherContext.tsx
  frontend/src/hooks/useNavigator.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/SeeTogetherTopics.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/router.tsx
Labels: FE, 우선순위 : 상, refactor

#553 [BE] Refactor/#540 지연로딩의 경우, soft delete을 반영할 수 없는 문제 해결
  backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/atlas/domain/AtlasRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/application/AuthService.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/domain/PermissionRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/presentation/PermissionController.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinImage.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinImageRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
  backend/src/main/resources/data-default.sql
  backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/auth/application/AuthServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/annotation/ServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/application/LocationQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinImageRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicRepositoryTest.java
Labels: bug, BE, 우선순위 : 상, refactor

#558 [BE] 삭제된 토픽, 핀이 보이는 버그 해결
  .github/workflows/be-merge-dev.yml
  .github/workflows/be-pull-request.yml
  backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/atlas/domain/AtlasRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/auth/application/AuthService.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/Member.java
  backend/src/main/java/com/mapbefine/mapbefine/member/domain/MemberInfo.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/domain/PermissionRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/presentation/PermissionController.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinImage.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinImageRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
  backend/src/main/resources/data-default.sql
  backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/auth/application/AuthServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/annotation/ServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/application/LocationQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinImageRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicRepositoryTest.java
Labels: bug, BE, 우선순위 : 상

#561 [BE] Refactor/#547 로그인 회원 프로필 조회 API 명세 변경
  backend/src/docs/asciidoc/member.adoc
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/presentation/MemberController.java
  backend/src/test/java/com/mapbefine/mapbefine/member/MemberIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
Labels: BE, 우선순위 : 중, refactor

#566 feat/#564 poi 적용
  .github/workflows/fe-merge-dev.yml
  frontend/src/apis/getPoiApi.ts
  frontend/src/components/common/Input/Autocomplete.tsx
  frontend/src/hooks/useClickedCoordinate.ts
  frontend/src/pages/NewPin.tsx
  frontend/src/types/Poi.ts
  frontend/src/types/tmap.d.ts
Labels: FE, 우선순위 : 상, feat

#575 [FE] hotfix env 이름 형식 통일
  .github/workflows/fe-merge-dev.yml
  frontend/src/apis/getPoiApi.ts
Labels: FE, env, 우선순위 : 상

#569 [FE] Feature/#560 메인 페이지에 swiper 및 배너 적용
  frontend/.eslintrc.js
  frontend/src/GlobalStyle.ts
  frontend/src/assets/banner_boong.webp
  frontend/src/assets/banner_usage.webp
  frontend/src/assets/swiper_left_button.svg
  frontend/src/assets/swiper_right_button.svg
  frontend/src/components/Banner/index.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicCardContainer/index.tsx
  frontend/src/components/TopicCardList/index.tsx
  frontend/src/components/common/Box/index.ts
  frontend/src/components/common/Grid/index.ts
  frontend/src/components/common/Space/MediaSpace.ts
  frontend/src/components/common/Swiper/Tab.tsx
  frontend/src/components/common/Swiper/hooks/useAutoplay.ts
  frontend/src/components/common/Swiper/hooks/useMatchMedia.ts
  frontend/src/components/common/Swiper/hooks/useSwipeable.ts
  frontend/src/components/common/Swiper/index.tsx
  frontend/src/components/common/Text/mediaText.ts
  frontend/src/components/common/Tooltip/index.tsx
  frontend/src/pages/Bookmark.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/Search.tsx
  frontend/src/pages/SeeAllLatestTopics.tsx
  frontend/src/pages/SeeAllNearTopics.tsx
  frontend/src/pages/SeeAllPopularTopics.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/types/index.d.ts
  frontend/webpack.common.js
Labels: FE, 우선순위 : 상, feat

#573 [FE] Refactor/#572 핀 이미지 태그로 교체 및 아이콘 소스 검토
  frontend/public/index.html
  frontend/src/assets/favoriteBtn_notFilled.svg
  frontend/src/assets/profile_defaultImage.svg
  frontend/src/assets/search.svg
  frontend/src/assets/seeTogetherBtn_filled.svg
  frontend/src/assets/seeTogetherBtn_notFilled.svg
  frontend/src/assets/setting.svg
  frontend/src/assets/topicInfo_seeTogetherBtn_notFilled.svg
  frontend/src/assets/topicInfo_shareUrl.svg
  frontend/src/assets/updateBtn.svg
  frontend/src/components/MyInfo/index.tsx
  frontend/src/components/PinImageContainer/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicCardContainer/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/components/common/Image/index.ts
  frontend/src/components/common/Image/index.tsx
  frontend/src/components/common/Text/MediaQueryText.ts
  frontend/src/constants/index.ts
  frontend/src/constants/pinImage.ts
  frontend/src/context/MarkerContext.tsx
  frontend/src/pages/Bookmark.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/Search.tsx
  frontend/src/pages/SeeAllLatestTopics.tsx
  frontend/src/pages/SeeAllNearTopics.tsx
  frontend/src/pages/SeeAllPopularTopics.tsx
Labels: FE, 우선순위 : 중, refactor

#580 [BE] Env/#545 무중단 배포를 위한 구성 파일 작성
  .github/workflows/be-merge-dev.yml
  .github/workflows/be-merge-prod.yml
Labels: BE, Infra

#581 [BE] env/#545 CI/CD 동작을 위한 개행 삭제
  backend/src/main/java/com/mapbefine/mapbefine/admin/presentation/AdminController.java
Labels: BE, Infra

#565 [BE] Refactor/#563 RestDocs 응답 오류(500) 해결 및 상태코드 검증 추가
  backend/src/docs/asciidoc/admin.adoc
  backend/src/docs/asciidoc/pin.adoc
  backend/src/docs/asciidoc/topic.adoc
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
  backend/src/test/java/com/mapbefine/mapbefine/admin/presentation/AdminControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/atlas/presentation/AtlasControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/auth/presentation/LoginControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/presentation/BookmarkControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/presentation/LocationControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/presentation/MemberControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/presentation/PermissionControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Labels: bug, BE, 우선순위 : 중, refactor

#582 [BE] feat: 토픽 이미지 수정 기능 구현
  backend/src/docs/asciidoc/topic.adoc
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/dto/request/TopicUpdateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
  backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/image/FileFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Labels: BE, 우선순위 : 상, feat

#583 [FE] Feature/#550 토픽 이미지 수정 및 핀 이미지 삭제 기능
  frontend/src/apis/putApi.ts
  frontend/src/assets/remove_image_icon.svg
  frontend/src/components/PinImageContainer/index.tsx
  frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
  frontend/src/pages/PinDetail.tsx
Labels: FE, 우선순위 : 상, feat

#590 [FE] Refactor/#578 지도 핀 Boundary 조정
  frontend/src/assets/currentLocationBtn.svg
  frontend/src/components/Map/index.tsx
  frontend/src/hooks/useGeolocation.ts
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/store/mapInstance.ts
  frontend/src/types/tmap.d.ts
Labels: FE, 우선순위 : 상, refactor

#584 [BE] Feat/#548 공간 인덱스 구현
  backend/build.gradle
  backend/src/main/java/com/mapbefine/mapbefine/location/application/LocationQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/location/domain/Coordinate.java
  backend/src/main/java/com/mapbefine/mapbefine/location/domain/LocationRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
  backend/src/test/java/com/mapbefine/mapbefine/DatabaseCleanup.java
  backend/src/test/java/com/mapbefine/mapbefine/MapbefineApplicationTests.java
  backend/src/test/java/com/mapbefine/mapbefine/TestDatabaseContainer.java
  backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/atlas/application/AtlasQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/auth/application/AuthServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/auth/application/TokenServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/IntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/RestDocsIntegration.java
  backend/src/test/java/com/mapbefine/mapbefine/common/annotation/RepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/annotation/ServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/application/LocationQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/location/domain/CoordinateTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/member/application/MemberQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/oauth/application/OauthServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/application/PermissionCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/application/PermissionQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinImageRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicRepositoryTest.java
Labels: BE, 우선순위 : 중, refactor

#591 [BE] Feat/#586 핀 수정 시 변경 이력 저장 이벤트 구현
  backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/atlas/domain/AtlasRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/history/application/PinHistoryCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/history/domain/PinHistory.java
  backend/src/main/java/com/mapbefine/mapbefine/history/domain/PinHistoryRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/domain/PermissionRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/event/PinUpdateEvent.java
  backend/src/main/resources/logback-spring.xml
  backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/history/application/PinHistoryCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/PinIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
Labels: BE, 우선순위 : 상, feat

#606 [BE] CI/CD 재 가동을 위한 공백 추가
  backend/Dockerfile-prod
Labels: BE

#608 [FE] Feat/#604 image swiper 적용 및 image size limit 적용
  frontend/src/components/PinImageContainer/index.tsx
  frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
Labels: FE, 우선순위 : 상, feat

#607 [FE] Refactor/#593 모아보기와 단일조회페이지 분리 및 리팩토링
  frontend/.eslintrc.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/AddSeeTogether/index.tsx
  frontend/src/components/Banner/index.tsx
  frontend/src/components/PinImageContainer/index.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/PinsOfTopic/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicCardContainer/index.tsx
  frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/components/common/Swiper/Tab.tsx
  frontend/src/components/common/Swiper/hooks/useAutoplay.ts
  frontend/src/components/common/Swiper/hooks/useMatchMedia.ts
  frontend/src/components/common/Swiper/hooks/useSwipeable.ts
  frontend/src/components/common/Swiper/index.tsx
  frontend/src/context/MarkerContext.tsx
  frontend/src/context/SeeTogetherContext.tsx
  frontend/src/hooks/useNavigator.ts
  frontend/src/hooks/useResizeMap.ts
  frontend/src/hooks/useSetNavbarHighlight.ts
  frontend/src/hooks/useTags.ts
  frontend/src/pages/AskLogin.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/SeeTogether.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/router.tsx
Labels: FE, 우선순위 : 상, refactor

#611 [FE] Hotfix/map panto 오류 수정
  frontend/src/components/Layout/index.tsx
  frontend/src/components/PullPin/index.tsx
  frontend/src/hooks/useFocusToMarkers.ts
Labels: bug, FE, 우선순위 : 상
