Repository woowacourse-teams/2023-map-befine, pull requests merged in 2023-11, with the labels that each got.

#618 [BE] Feature/#614 클러스터링 기능 구현
  backend/src/docs/asciidoc/topic.adoc
  backend/src/main/java/com/mapbefine/mapbefine/location/domain/Coordinate.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Cluster.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Clusters.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/ClusterResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/dto/response/RenderPinResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/exception/TopicErrorCode.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/ClusterTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/ClustersTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Labels: BE, feat

#615 [FE] Refactor/#613 지도 클러스터링 기능 추가 및 지도 상태 리팩토링
  frontend/.eslintrc.js
  frontend/src/components/Map/index.tsx
  frontend/src/components/common/Flex/index.ts
  frontend/src/constants/index.ts
  frontend/src/constants/pinImage.ts
  frontend/src/context/MarkerContext.tsx
  frontend/src/hooks/useAnimateClickedPin.ts
  frontend/src/hooks/useClickedCoordinate.ts
  frontend/src/hooks/useFocusToMarkers.ts
  frontend/src/hooks/useMapClick.ts
  frontend/src/hooks/useUpdateCoordinates.ts
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/store/mapInstance.ts
  frontend/src/types/tmap.d.ts
Labels: FE, 우선순위 : 상, feat, refactor

#621 [BE] Hotfix/#619 핀 삭제 시 토픽의 핀 개수가 업데이트되지 않는 버그 해결
  backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
  backend/src/test/java/com/mapbefine/mapbefine/admin/AdminIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
Labels: bug, BE, 우선순위 : 상

#622 [FE] Refactor/#620 모아보기 클러스터링
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/PullPin/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/constants/pinImage.ts
  frontend/src/context/MarkerContext.tsx
  frontend/src/hooks/useClickedCoordinate.ts
  frontend/src/hooks/useRealDistanceOfPin.ts
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SeeTogether.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/types/tmap.d.ts
Labels: FE, 우선순위 : 상, refactor

#623 [FE] Refactor 지도 회전 및 기울기 이벤트 시 지도를 원래대로 조정
  frontend/src/pages/SeeTogether.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/types/tmap.d.ts
Labels: FE, refactor

#624 [FE] 2.1.0 배포
  frontend/.eslintrc.js
  frontend/src/components/Map/index.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/PullPin/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/components/common/Flex/index.ts
  frontend/src/constants/index.ts
  frontend/src/constants/pinImage.ts
  frontend/src/context/MarkerContext.tsx
  frontend/src/hooks/useAnimateClickedPin.ts
  frontend/src/hooks/useClickedCoordinate.ts
  frontend/src/hooks/useFocusToMarkers.ts
  frontend/src/hooks/useMapClick.ts
  frontend/src/hooks/useRealDistanceOfPin.ts
  frontend/src/hooks/useUpdateCoordinates.ts
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SeeTogether.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/store/mapInstance.ts
  frontend/src/types/tmap.d.ts
Labels: FE, 우선순위 : 상, feat
