Repository woowacourse-teams/2023-map-befine, pull requests merged in 2023-09, with the labels that each got.

#367 [BE] Fix/#366 테스트 수행 시 로그 패턴 깨지는 오류 해결
  .github/workflows/be-merge-dev.yml
  .github/workflows/be-pull-request.yml
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback-spring.xml
  backend/src/test/resources/application.yml
  backend/src/test/resources/logback-spring.xml
  backend/src/test/resources/logback-test.xml
Labels: bug, BE, 우선순위 : 중

#371 [BE] Refactor/#370 DatabaseCleanup JdbcTemplate 적용
  backend/src/test/java/com/mapbefine/mapbefine/DatabaseCleanup.java
Labels: BE, 우선순위 : 중, refactor

#377 [BE] Refactor/#376 로깅 환경 개선을 위한 설정 파일 리팩터링
  backend/.gitignore
  backend/build.gradle
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/console-appender.xml
  backend/src/main/resources/file-debug-appender.xml
  backend/src/main/resources/file-error-appender.xml
  backend/src/main/resources/file-hibernate-appender.xml
  backend/src/main/resources/file-info-appender.xml
  backend/src/main/resources/file-warn-appender.xml
  backend/src/main/resources/logback-spring.xml
  backend/src/test/resources/application.yml
  backend/src/test/resources/logback-spring.xml
Labels: BE, env, 우선순위 : 중, refactor

#383 [FE] Hotfix/solve login error
  frontend/src/pages/AskLogin.tsx
Labels: FE

#396 [BE] S3 를 통한 Image Upload 기능 추가 테스트
  backend/src/main/java/com/mapbefine/mapbefine/common/config/S3Config.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/presentation/TopicController.java
Labels: BE, 우선순위 : 중, feat

#397 [BE] Hotfix/log Info, Debug 레벨 커스텀 로그만 출력하도록 변경
  backend/src/main/resources/logback-spring.xml
Labels: BE, 우선순위 : 상, refactor

#387 [FE] Feature/#382 반응형 대응
  .github/workflows/fe-merge-dev.yml
  .github/workflows/fe-pull-request.yml
  frontend/cypress.config.ts
  frontend/cypress/e2e/mapbefine.cy.ts
  frontend/src/components/InputContainer/index.tsx
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/components/Map/index.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/components/ModalMyTopicList/addToMyTopicList.tsx
  frontend/src/components/ModalMyTopicList/index.tsx
  frontend/src/components/MyInfo/index.tsx
  frontend/src/components/PinsOfTopic/index.tsx
  frontend/src/components/PullPin/index.tsx
  frontend/src/components/Toast/index.tsx
  frontend/src/components/TopicCardContainer/index.tsx
  frontend/src/components/TopicCardList/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/responsive.ts
  frontend/src/pages/Bookmark.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/KakaoRedirect.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/RootPage.tsx
  frontend/src/pages/SeeAllLatestTopics.tsx
  frontend/src/pages/SeeAllNearTopics.tsx
  frontend/src/pages/SeeAllPopularTopics.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/pages/UpdatedPinDetail.tsx
  frontend/src/router.tsx
Labels: FE, design, 우선순위 : 상, feat

#401 [BE] feat/#386 Pin 생성 시 Image Upload 테스트
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/presentation/PinController.java
  backend/src/main/java/com/mapbefine/mapbefine/s3/application/S3ServiceImpl.java
  backend/src/main/java/com/mapbefine/mapbefine/s3/domain/UploadFile.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/PinIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
Labels: BE, 우선순위 : 중, ALL, feat

#398 [FE] Refactor/#395 지도 타입 지정 및 Map 컴포넌트 리팩토링
  frontend/package-lock.json
  frontend/src/components/Layout/index.tsx
  frontend/src/components/Map/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/context/CoordinatesContext.tsx
  frontend/src/context/MarkerContext.tsx
  frontend/src/context/NavbarHighlightsContext.tsx
  frontend/src/hooks/useAnimateClickedPin.ts
  frontend/src/hooks/useClickedCoordinate.ts
  frontend/src/hooks/useFocusToMarkers.ts
  frontend/src/hooks/useMapClick.ts
  frontend/src/hooks/useSetNavbarHighlight.ts
  frontend/src/hooks/useUpdateCoordinates.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/pages/UpdatedPinDetail.tsx
  frontend/src/types/FormValues.ts
  frontend/src/types/index.d.ts
  frontend/src/types/tmap.d.ts
  frontend/tsconfig.json
Labels: FE, 우선순위 : 중, refactor

#403 [FE] Fix/ 머지 후 충돌 해결
  frontend/src/components/Layout/index.tsx
Labels: FE

#394 [FE] Test/#369 Jest 커스텀 훅 테스트 추가
  frontend/babel.config.js
  frontend/src/__tests__/hooks/useFormValues.test.ts
  frontend/src/__tests__/hooks/validation.test.ts
  frontend/src/validations/index.ts
Labels: FE, 우선순위 : 중, test

#412 [BE] Refactor/#406 토픽 권한을 가진 회원 목록 조회 시 공개 여부를 함께 반환하도록 변경
  backend/src/docs/asciidoc/member.adoc
  backend/src/docs/asciidoc/permission.adoc
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/domain/Permission.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/dto/response/PermissionMemberDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/dto/response/PermissionedMemberResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/dto/response/TopicAccessDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/presentation/PermissionController.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicStatus.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/exception/TopicException.java
  backend/src/test/java/com/mapbefine/mapbefine/atlas/AtlasIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/BookmarkIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/common/IntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/PermissionIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/application/PermissionQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/presentation/PermissionControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/PinIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/presentation/PinControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/presentation/TopicControllerTest.java
Labels: BE, 우선순위 : 상, refactor

#410 [FE] Refactor/#402 지도 및 핀 권한 부여 여부 확인 및 지도 수정 페이지 구현
  frontend/src/apiHooks/useDelete.ts
  frontend/src/apiHooks/usePost.ts
  frontend/src/apiHooks/usePut.ts
  frontend/src/components/AuthorityRadioContainer/index.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/components/ModalMyTopicList/addToMyTopicList.tsx
  frontend/src/components/PinsOfTopic/index.tsx
  frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/mocks/handlers.js
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/UpdatedPinDetail.tsx
  frontend/src/types/Pin.ts
  frontend/src/types/Topic.ts
Labels: FE, 우선순위 : 상, refactor

#425 [BE] Fix/#424 refresh token duplicated
  backend/src/main/java/com/mapbefine/mapbefine/auth/infrastructure/JwtTokenProvider.java
  backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java
Labels: bug, BE, 우선순위 : 상

#409 [FE] Feat/#386 지도, 핀 이미지에 s3 적용
  frontend/src/apis/getApi.ts
  frontend/src/apis/postApi.ts
  frontend/src/apis/putApi.ts
  frontend/src/components/PinImageContainer/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/types/FormValues.ts
  frontend/src/types/Pin.ts
Labels: FE, 우선순위 : 상, feat

#458 [BE]Hotfix/cors allowCredentials 설정 추가
  backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java
Labels: bug, BE, 우선순위 : 상

#462 [BE] Hotfix/cors allowHeaders 와일드카드 적용
  backend/src/main/java/com/mapbefine/mapbefine/common/config/WebConfig.java
Labels: bug, BE, 우선순위 : 상

#419 [FE] Fix/permission 토픽 권한 수정 오류 해결
  frontend/cypress.config.ts
  frontend/cypress/e2e/mapbefine.cy.ts
  frontend/src/components/AuthorityRadioContainer/index.tsx
  frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/types/Topic.ts
Labels: bug, FE, 우선순위 : 상

#436 [FE] Feature/#435 이미지 압축 기능 구현
  frontend/src/hooks/useCompressImage.ts
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
Labels: FE, 우선순위 : 상, feat

#423 [ FE ] Refactor/#404 홈페이지 및 Navbar 리팩토링
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Layout/NavbarItem.tsx
  frontend/src/hooks/useNavigator.ts
  frontend/src/pages/Home.tsx
Labels: FE, 우선순위 : 중, refactor

#474 [FE] 토큰 재발급 로직 모든 메소드에 적용
  frontend/src/apis/deleteApi.ts
  frontend/src/apis/getApi.ts
  frontend/src/apis/postApi.ts
  frontend/src/apis/putApi.ts
  frontend/src/apis/utils.ts
Labels: FE, 우선순위 : 상, feat

#476 [FE] Refactor/#469 동적 임포트와 tree shaking으로 코드 스플리팅
  frontend/babel.config.js
  frontend/src/router.tsx
Labels: FE, 우선순위 : 상, refactor

#477 [FE] Fix/#472 토픽 수정 시 권한 수정 보류
  frontend/src/components/AuthorityRadioContainer/index.tsx
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
Labels: bug, FE, 우선순위 : 상

#478 [FE] Hotfix 동적 임포트에 suspense 적용
  frontend/src/router.tsx
Labels: FE, 우선순위 : 상, refactor

#486 [FE] Refactor/#481 개발 서버 QA 후 발생한 이슈 해결
  frontend/src/apiHooks/usePost.ts
  frontend/src/apis/postApi.ts
  frontend/src/components/Modal/index.tsx
  frontend/src/components/ModalMyTopicList/addToMyTopicList.tsx
  frontend/src/components/PinImageContainer/index.tsx
Labels: FE, 우선순위 : 상, refactor

#491 [FE] Feature/#489 사용자 입력 시 개행 적용
  .github/workflows/fe-merge-dev.yml
  .github/workflows/fe-pull-request.yml
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/InputContainer/index.tsx
  frontend/src/components/common/Text/index.ts
  frontend/src/components/common/Textarea/index.ts
  frontend/src/constants/index.ts
Labels: FE, 우선순위 : 상, feat

#496 [FE] Feature/#495 Google Analytics 적용
  frontend/package-lock.json
  frontend/package.json
  frontend/src/router.tsx
Labels: FE, 우선순위 : 상, feat

#492 [FE] 개행 처리 적용 시 wrap 속성이 적용되지 않던 오류 수정
  frontend/src/components/common/Text/index.ts
Labels: bug, FE, 우선순위 : 상

#497 [FE] Refactor/#495 GA 패키지 json
  frontend/package-lock.json
  frontend/package.json
Labels: FE, 우선순위 : 상

#498 [FE] Refactor/#495 ga 추적 key 상수로 변경
  frontend/src/router.tsx
Labels: FE, 우선순위 : 상, refactor

#499 [FE] Refactor/495 GA 위치 변경
  frontend/src/App.tsx
  frontend/src/router.tsx
Labels: FE, 우선순위 : 상, refactor

#501 [FE] refactor/#495 Google Analytics 불필요한 코드 삭제 및 최종본
  frontend/src/App.tsx
Labels: FE, 우선순위 : 상, refactor

#506 [FE] Refactor/#505 react ga4 적용
  .github/workflows/fe-merge-dev.yml
  .github/workflows/fe-merge-prod.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/mockServiceWorker.js
  frontend/src/App.tsx
  frontend/src/utils/RouteChangeTracker.tsx
Labels: FE, 우선순위 : 상, refactor

#507 [FE] Hotfix react ga4 에러 해결
  frontend/src/App.tsx
  frontend/src/index.tsx
  frontend/src/pages/RootPage.tsx
Labels: bug, FE, 우선순위 : 상

#508 [BE] Refactor/#494 성능 개선을 위한 조회 쿼리 수정
  backend/src/main/java/com/mapbefine/mapbefine/atlas/domain/AtlasRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/domain/BookmarkRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/location/domain/Location.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
  backend/src/test/java/com/mapbefine/mapbefine/admin/AdminIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/auth/application/TokenServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/domain/PermissionTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
Labels: BE, 우선순위 : 상, refactor

#514 [FE] Refactor/#513 지도 생성 및 핀 생성 페이지 지도 위치 조정
  frontend/src/components/Layout/index.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/SeeTogetherTopics.tsx
Labels: FE, 우선순위 : 상, refactor

#515 [FE] Fix/myinfo 마이페이지 닉네임 변경 시 이미지 사라지던 오류 수정
  frontend/src/components/MyInfo/UpdateMyInfo.tsx
  frontend/src/components/MyInfo/index.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/Home.tsx
  frontend/src/types/Profile.ts
Labels: bug, FE, 우선순위 : 상

#517 [BE] 토픽 목록의 순서를 유지하기 위한 자료 구조 변경
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
Labels: bug, BE

#518 [BE] 기존의 HashSet 을 LinkedHashSet 으로 변경
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
Labels: bug, BE

#519 Hotfix: 토픽 조회시 순서 보장하도록 수정
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
  backend/src/test/java/com/mapbefine/mapbefine/permission/domain/PermissionTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
Labels: bug, BE, 우선순위 : 상

#523 [FE] Fix/#522 토픽 조회 중복 요청 오류, 핀 조회 시 토픽 조회 요청 오류 및 지도 줌인 오류 수정
  frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/context/MarkerContext.tsx
  frontend/src/hooks/useAnimateClickedPin.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/webpack.common.js
Labels: bug, FE, env, 우선순위 : 상

#521 [BE] Hotfix/#473 Soft Delete 반영해 조회하도록 쿼리 수정
  backend/src/main/java/com/mapbefine/mapbefine/admin/application/AdminCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/atlas/application/AtlasCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/bookmark/application/BookmarkCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/member/application/MemberQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/permission/application/PermissionQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/application/PinQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinImageRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/pin/domain/PinRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/application/TopicQueryService.java
  backend/src/main/java/com/mapbefine/mapbefine/topic/domain/TopicRepository.java
  backend/src/test/java/com/mapbefine/mapbefine/admin/application/AdminCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/application/PinQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/pin/domain/PinImageRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/application/TopicQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/topic/domain/TopicRepositoryTest.java
Labels: BE, 우선순위 : 상, refactor

#525 [FE] fix/#524 모아보기 상태에서 핀 조회가 안되는 오류 수정
  frontend/src/components/PinsOfTopic/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/pages/SelectedTopic.tsx
Labels: bug, FE, 우선순위 : 상

#527 [FE] Refactor/#526 반응형 네브바 가림 문제 해결
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/components/Map/index.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/constants/index.ts
  frontend/src/pages/AskLogin.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/KakaoRedirect.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/pages/PinDetail.tsx
Labels: FE, design, 우선순위 : 상

#528 [FE] 1.0.0 배포
  .github/workflows/fe-merge-dev.yml
  .github/workflows/fe-merge-prod.yml
  .github/workflows/fe-pull-request.yml
  frontend/jest.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/apiHooks/usePatch.ts
  frontend/src/apis/patchApi.ts
  frontend/src/assets/setting.svg
  frontend/src/components/InputContainer/index.tsx
  frontend/src/components/Layout/Navbar.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/components/Map/index.tsx
  frontend/src/components/Modal/index.tsx
  frontend/src/components/MyInfo/UpdateMyInfo.tsx
  frontend/src/components/MyInfo/index.tsx
  frontend/src/components/PinsOfTopic/index.tsx
  frontend/src/components/TopicInfo/UpdatedTopicInfo.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/components/common/Button/index.ts
  frontend/src/components/common/Text/index.ts
  frontend/src/components/common/Textarea/index.ts
  frontend/src/constants/index.ts
  frontend/src/context/MarkerContext.tsx
  frontend/src/hooks/useAnimateClickedPin.ts
  frontend/src/index.tsx
  frontend/src/pages/AskLogin.tsx
  frontend/src/pages/KakaoRedirect.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/NotFound.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/RootPage.tsx
  frontend/src/pages/SeeTogetherTopics.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/types/Profile.ts
  frontend/src/utils/RouteChangeTracker.tsx
  frontend/webpack.common.js
Labels: FE

#530 [FE] hotfix 운영서버 GA 코드 심기
  frontend/public/index.html
Labels: FE, 우선순위 : 상, feat

#531 [FE] design: 반응형 사이즈에서 로고 영역 배경 투명하게 적용
  frontend/src/components/Layout/index.tsx
Labels: FE, design, 우선순위 : 상
