Repository woowacourse-teams/2023-map-befine, pull requests merged in 2023-07, with the labels that each got.

#15 [BE]Chore/#14 백엔드 개발 환경 초기 설정
  backend/.gitignore
  backend/build.gradle
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/mapbefine/mapbefine/MapbefineApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/mapbefine/mapbefine/MapbefineApplicationTests.java
Labels: BE, env, 우선순위 : 상

#26 [FE]Chore/#25 eslint settings error 해결
  frontend/.eslintrc.js
Labels: FE, env

#27 [FE]Design/#12 ThemeProvider와 GlobalStyle 공통 스타일 속성 지정
  frontend/src/GlobalStyle.ts
  frontend/src/index.tsx
  frontend/src/themes/color.ts
  frontend/src/themes/fontSize.ts
  frontend/src/themes/index.ts
  frontend/src/themes/radius.ts
  frontend/src/themes/spacing.ts
Labels: FE, design

#28 토픽, 핀에 대한 Entity 및 뼈대코드 작성
  backend/src/main/java/com/mapbefine/mapbefine/MapbefineApplication.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/BaseEntity.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/CityDo.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Coordinate.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/GuGun.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/LegalDong.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Location.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/UserPin.java
  backend/src/main/resources/application.properties
Labels: BE, feat

#30 [FE]Feat/#16 공통 컴포넌트 구현
  frontend/src/App.tsx
  frontend/src/components/common/Box/index.ts
  frontend/src/components/common/Button/index.ts
  frontend/src/components/common/Flex/index.ts
  frontend/src/components/common/Input/index.ts
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/common/Text/index.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/Topics.tsx
  frontend/src/themes/fontWeight.ts
  frontend/src/themes/index.ts
Labels: FE, feat

#34 [FE]Feat/#33 스페이싱 공통 컴포넌트 구현
  frontend/src/components/common/Space/index.ts
Labels: FE, feat

#37 [Docs] GitHub Issue 및 PR Template 설정
  .github/ISSUE_TEMPLATE/bug.yml 
  .github/ISSUE_TEMPLATE/deploy.yml 
  .github/ISSUE_TEMPLATE/env.yml
  .github/ISSUE_TEMPLATE/feat.yml
  .github/ISSUE_TEMPLATE/meeting.yml
  .github/ISSUE_TEMPLATE/refactor.yml 
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
Labels: docs, 우선순위 : 상, ALL

#50 [FE]Feat/#13 React Router 기능 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/src/App.tsx
  frontend/src/index.tsx
Labels: FE, feat

#51 [FE]Feat/#49 MSW 환경 설정
  frontend/public/mockServiceWorker.js
  frontend/src/index.tsx
  frontend/src/mocks/browser.js
  frontend/src/mocks/handlers.js
Labels: FE, feat

#53 [FE]Feat/#32 PinDetail 페이지 컴포넌트 구현
  frontend/src/assets/clipping.svg
  frontend/src/assets/plus.svg
  frontend/src/assets/share.svg
  frontend/src/assets/showDetail.svg
  frontend/src/index.d.ts
  frontend/src/pages/PinDetail.tsx
Labels: FE, feat

#54 [FE]Refactor/#52 공통 컴포넌트 속성 변경
  frontend/src/components/common/Box/index.ts
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/common/Text/index.ts
Labels: FE

#60 [FE]Feat/#35 토픽 목록 및 핀 목록 페이지 구현
  frontend/src/components/common/Box/index.ts
  frontend/src/components/common/Layout/index.tsx
  frontend/src/components/common/PinPreview/index.tsx
  frontend/src/components/common/Topic/index.tsx
  frontend/src/components/common/TopicCard/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/Pins.tsx
  frontend/src/pages/Topics.tsx
Labels: FE, feat

#66 [FE]Feat/#64 라우터 지정 및 상태 관리
  frontend/src/App.tsx
  frontend/src/assets/logo.svg
  frontend/src/components/Layout/Logo.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/components/common/Box/index.ts
  frontend/src/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/RootPage.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/router.tsx
  frontend/src/types/Pin.ts
  frontend/src/types/Topic.ts
  frontend/src/types/index.d.ts
Labels: FE, feat

#67 [FE]Feat/#65 MSW get, post 및 Api 구현
  frontend/src/mocks/db/getDetailTopic.json
  frontend/src/mocks/db/getTopics.json
  frontend/src/mocks/handlers.js
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/utils/getApi.ts
  frontend/src/utils/postApi.ts
Labels: FE, feat

#68 [BE} 핀 관련 기능 구현 완료 (테스트 제외) #63
  backend/docs/README.md
  backend/src/main/java/com/mapbefine/mapbefine/controller/PinController.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinCreationRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinModificationRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/BaseEntity.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Coordinate.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Location.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/UserPin.java
  backend/src/main/java/com/mapbefine/mapbefine/repository/LocationRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/repository/PinRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/repository/UserPinRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/service/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/service/PinQueryService.java
  backend/src/test/java/com/mapbefine/mapbefine/entity/CoordinateTest.java
  backend/src/test/java/com/mapbefine/mapbefine/repository/LocationRepositoryTest.java
Labels: BE, 우선순위 : 상, feat

#69 [BE] 토픽 관련 기능 구현
  backend/docs/README.md
  backend/src/main/java/com/mapbefine/mapbefine/controller/PinController.java
  backend/src/main/java/com/mapbefine/mapbefine/controller/TopicController.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinCreateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinUpdateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicCreateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicMergeRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicUpdateDto.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicUpdateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Coordinate.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Location.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/repository/PinRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/service/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/service/TopicCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/service/TopicQueryService.java
  backend/src/test/java/com/mapbefine/mapbefine/entity/CoordinateTest.java
  backend/src/test/java/com/mapbefine/mapbefine/integration/IntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/integration/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/repository/LocationRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/service/TopicCommandServiceTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/data.sql
Labels: BE, 우선순위 : 상, feat

#73 [FE]Test/#72 공통 컴포넌트 스토리북 구현
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/.storybook/preview.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/Box/index.stories.ts
  frontend/src/components/common/Button/index.stories.ts
  frontend/src/components/common/Input/index.stories.ts
  frontend/src/components/common/Text/index.stories.ts
  frontend/src/components/common/Textarea/index.stories.ts
Labels: FE, feat

#74 [BE] 현재 위치 인기 토픽 조회 기능 구현
  backend/docs/README.md
  backend/src/main/java/com/mapbefine/mapbefine/controller/TopicController.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicFindBestRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/repository/LocationRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/repository/PinRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/repository/TopicRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/service/TopicCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/service/TopicQueryService.java
  backend/src/test/java/com/mapbefine/mapbefine/LocationFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/PinFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/TopicFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/integration/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/service/TopicCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/service/TopicQueryServiceTest.java
  backend/src/test/resources/data.sql
  backend/src/test/resources/topic-fixture.sql
Labels: BE, 우선순위 : 상, feat

#75 [BE] 핀 기능 관련 테스트 구현
  .idea/inspectionProfiles/Project_Default.xml
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinCreateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Coordinate.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Location.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/repository/PinRepository.java
  backend/src/main/java/com/mapbefine/mapbefine/service/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/service/PinQueryService.java
  backend/src/test/java/com/mapbefine/mapbefine/PinFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/entity/PinTest.java
  backend/src/test/java/com/mapbefine/mapbefine/repository/LocationRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/repository/PinRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/service/PinCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/service/PinQueryServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/service/TopicCommandServiceTest.java
Labels: BE, 우선순위 : 상, test

#78 [FE]Feat/#77 핀 디테일 수정하기 페이지 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/index.tsx
  frontend/src/mocks/handlers.js
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/utils/putApi.ts
Labels: FE, feat

#80 [BE] cors를 위한 WebMvcConfig 구현
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/src/main/java/com/mapbefine/mapbefine/config/WebMvcConfig.java
Labels: BE, env, 우선순위 : 상, feat

#93 [BE] 핀 생성 요청 DTO 수정
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinCreateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Coordinate.java
  backend/src/main/java/com/mapbefine/mapbefine/service/PinCommandService.java
  backend/src/test/java/com/mapbefine/mapbefine/service/PinCommandServiceTest.java
Labels: BE, 우선순위 : 상, refactor

#91 [BE] RestDocs API 문서화
  backend/build.gradle
  backend/gradlew
  backend/gradlew.bat
  backend/src/docs/asciidoc/index.adoc
  backend/src/docs/asciidoc/pin.adoc
  backend/src/docs/asciidoc/topic.adoc
  backend/src/main/java/com/mapbefine/mapbefine/controller/PinController.java
  backend/src/test/java/com/mapbefine/mapbefine/controller/PinControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/controller/RestDocsIntegration.java
  backend/src/test/java/com/mapbefine/mapbefine/controller/TopicControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/integration/IntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/integration/TopicIntegrationTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/initialization.sql
Labels: docs, BE, 우선순위 : 상

#94 [BE] PinCreateRequest 변경에 따른 테스트 코드 수정
  backend/src/test/java/com/mapbefine/mapbefine/controller/PinControllerTest.java
Labels: BE, 우선순위 : 상, refactor

#96 [BE] Controller RequestBody 누락으로 인한 코드 수정
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug.yml 
  .github/ISSUE_TEMPLATE/deploy.yml
  .github/ISSUE_TEMPLATE/deploy.yml 
  .github/ISSUE_TEMPLATE/env.yml
  .github/ISSUE_TEMPLATE/feat.yml
  .github/ISSUE_TEMPLATE/meeting.yml
  .github/ISSUE_TEMPLATE/refactor.yml
  .github/ISSUE_TEMPLATE/refactor.yml 
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  backend/src/main/java/com/mapbefine/mapbefine/controller/PinController.java
Labels: bug, BE, 우선순위 : 상

#98 [FE]Feat/#97 시맨틱 태그 적용
  frontend/src/GlobalStyle.ts
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
Labels: FE, feat

#103 [FE]Test/#102 공통 컴포넌트 이외의 컴포넌트 스토리북 코드 작성
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/.storybook/public/mockServiceWorker.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/PinPreview/index.stories.ts
  frontend/src/components/TopicCard/TopicCard.stories.ts
  frontend/src/components/TopicInfo/index.stories.ts
  frontend/src/pages/Home.stories.ts
  frontend/src/pages/NewTopic.stories.ts
  frontend/src/pages/PinDetail.stories.ts
  frontend/webpack.dev.js
Labels: FE, feat

#105 [FE]Refactor/#104 스프린트 2 이후 전반적인 코드 리팩토링
  frontend/src/components/Layout/Logo.tsx
  frontend/src/components/Layout/index.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/hooks/useFormValues.ts
  frontend/src/hooks/useNavigator.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/pages/UpdatedPinDetail.tsx
  frontend/src/types/FormValues.ts
Labels: FE, 우선순위 : 상, refactor

#108 [BE] 깃허브 액션 설정 (CI)
  .github/workflows/gradle.yml
Labels: BE, Infra, 우선순위 : 중

#110 [BE] API 명세 수정에 따른 Image 구현
  backend/src/main/java/com/mapbefine/mapbefine/controller/PinController.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinCreateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/PinUpdateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicCreateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicDetailResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicMergeRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicResponse.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/PinImage.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/service/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/service/TopicCommandService.java
  backend/src/test/java/com/mapbefine/mapbefine/TopicFixture.java
  backend/src/test/java/com/mapbefine/mapbefine/controller/PinControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/controller/TopicControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/entity/PinTest.java
  backend/src/test/java/com/mapbefine/mapbefine/integration/IntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/integration/PinIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/integration/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/repository/PinRepositoryTest.java
  backend/src/test/java/com/mapbefine/mapbefine/service/PinCommandServiceTest.java
  backend/src/test/java/com/mapbefine/mapbefine/service/PinQueryServiceTest.java
  backend/src/test/resources/initialization.sql
  backend/src/test/resources/topic-fixture.sql
Labels: BE, 우선순위 : 중, feat

#106 [BE] 핀 관련 기능 코드 리팩토링 #90
  backend/src/main/java/com/mapbefine/mapbefine/controller/PinController.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Coordinate.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Pin.java
  backend/src/main/java/com/mapbefine/mapbefine/service/PinCommandService.java
  backend/src/main/java/com/mapbefine/mapbefine/service/TopicCommandService.java
  backend/src/test/java/com/mapbefine/mapbefine/entity/CoordinateTest.java
  backend/src/test/java/com/mapbefine/mapbefine/entity/PinTest.java
  backend/src/test/java/com/mapbefine/mapbefine/repository/LocationRepositoryTest.java
Labels: BE, 우선순위 : 상, refactor

#112 [BE] API 명세 수정에 따른 Image 구현 - 토픽 수정 관련 누락 보완
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicUpdateDto.java
  backend/src/main/java/com/mapbefine/mapbefine/dto/TopicUpdateRequest.java
  backend/src/main/java/com/mapbefine/mapbefine/entity/Topic.java
  backend/src/main/java/com/mapbefine/mapbefine/service/TopicCommandService.java
  backend/src/test/java/com/mapbefine/mapbefine/controller/TopicControllerTest.java
  backend/src/test/java/com/mapbefine/mapbefine/integration/TopicIntegrationTest.java
  backend/src/test/java/com/mapbefine/mapbefine/service/TopicCommandServiceTest.java
Labels: BE, refactor

#120 [BE] Github Action workflows CD 추가
  .github/workflows/gradle.yml
Labels: BE, Infra, env, 우선순위 : 중

#114 [BE] Cors 권한 추가 설정
  backend/src/main/java/com/mapbefine/mapbefine/config/WebMvcConfig.java
Labels: BE, 우선순위 : 중, refactor

#115 [FE]Refactor/#109 수정된 API 명세 맞추기 및 백엔드와 연결
  frontend/.env
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/TopicCard/TopicCard.stories.ts
  frontend/src/components/TopicCard/index.tsx
  frontend/src/index.tsx
  frontend/src/mocks/db/detailTopic.js
  frontend/src/mocks/db/tempPins.js
  frontend/src/mocks/db/topics.js
  frontend/src/mocks/handlers.js
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/UpdatedPinDetail.tsx
  frontend/src/types/FormValues.ts
  frontend/src/types/Topic.ts
  frontend/src/utils/getApi.ts
  frontend/src/utils/postApi.ts
  frontend/src/utils/putApi.ts
  frontend/webpack.common.js
Labels: FE, refactor

#122 [BE] Github Action workflows CD refactoring
  .github/workflows/merge.yml
  .github/workflows/pull-request.yml
  backend/build.gradle
Labels: BE, Infra, env, 우선순위 : 중

#130 [BE] 개발 서버 배포 자동화 쉘 스크립트 작성 #81
  backend/deploy.sh
Labels: BE, Infra, 우선순위 : 중

#132 [BE] 개발서버 DB H2에서 MySQL로 이관
  backend/build.gradle
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
Labels: BE, Infra, env

#128 [FE] Feature/#116 토픽 및 핀 병합할 때 태그 추가되는 기능 구현
  frontend/src/components/MergeOrSeeTogether/index.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/common/Flex/index.ts
  frontend/src/components/common/Tag/index.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/SelectedTopic.tsx
Labels: FE, feat

#137 [FE] Feature/#129 토픽, 핀 병합 및 같이보기 기능 구현
  frontend/.env
  frontend/src/App.tsx
  frontend/src/components/MergeOrSeeTogether/index.tsx
  frontend/src/components/PinPreview/index.tsx
  frontend/src/components/TopicCard/TopicCard.stories.ts
  frontend/src/components/TopicCard/index.tsx
  frontend/src/components/TopicInfo/index.tsx
  frontend/src/hooks/useNavigator.ts
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/NewTopic.tsx
  frontend/src/pages/PinDetail.stories.ts
  frontend/src/pages/PinDetail.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/pages/UpdatedPinDetail.tsx
  frontend/src/store/TagId.tsx
  frontend/src/store/TopicsId.tsx
  frontend/src/types/FormValues.ts
  frontend/src/types/Topic.ts
  frontend/webpack.common.js
Labels: FE, feat

#138 [FE] 지도 UI 적용
  frontend/public/index.html
  frontend/src/components/Layout/index.tsx
  frontend/src/components/Map.tsx
  frontend/src/components/common/Flex/index.ts
  frontend/src/context/CoordinatesContext.tsx
  frontend/src/context/MarkerContext.tsx
  frontend/src/hooks/useGeolocation.ts
  frontend/src/index.tsx
  frontend/src/mocks/db/detailTopic.js
  frontend/src/mocks/db/tempPins.js
  frontend/src/pages/Home.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/webpack.dev.js
Labels: FE, feat

#140 [FE]Refactor/#139 머지 후 싱크 및 에러 해결 작업
  frontend/src/components/Map.tsx
  frontend/src/components/TopicCard/index.tsx
  frontend/src/pages/NewPin.tsx
  frontend/src/pages/SelectedTopic.tsx
  frontend/src/utils/getAddress.ts
Labels: FE, refactor

#135 [BE] 개발 및 운영 서버 구성 파일 및 CI/CD 설정 분리
  .github/workflows/be-merge-dev.yml
  .github/workflows/be-merge-prod.yml
  .github/workflows/be-pull-request.yml
  backend/src/main/resources/application-prod.yml
Labels: BE, Infra, env, 우선순위 : 중

#136 [ FE] 프론트엔드 Github Action workflows CD 추가
  .github/workflows/fe-merge-dev.yml
  .github/workflows/fe-merge-prod.yml
Labels: FE, Infra, env
